export const LOGIN_USER = 'LOGIN_USER'
export const ERR_LOGIN_USER = 'ERR_LOGIN_USER'
export const REGISTER_USER = 'REGISTER_USER'
export const FETCH_COURSES = 'FETCH_COURSES'
export const ERR_FETCH_COURSES = 'ERR_FETCH_COURSES'
export const VERIFY_USER = 'VERIFY_USER'
export const GET_USER_FROM_RESPONSE = 'GET_USER_FROM_RESPONSE'
export const STORE_TOKEN = 'STORE_TOKEN'
export const AUTH_LOADING_STATE = 'AUTH_LOADING_STATE'
export const ASYNC_ERROR = 'ASYNC_ERROR'
export const ASYNC_ERRORS = 'ASYNC_ERRORS'
export const NULL_ERRORS = 'NULL_ERRORS'


export const FETCH_10_COURSES = 'FETCH_10_COURSES'
export const ALL_COURSES = 'ALL_COURSES'
export const FETCH_PO_COURSES = 'FETCH_PO_COURSES'
export const FETCH_COTF_COURSES = 'FETCH_COTF_COURSES'
export const FETCH_FREE_COURSES = 'FETCH_FREE_COURSES'
export const SHOW_COURSE = 'SHOW_COURSE'
export const ERR_SHOW_COURSE = 'ERR_SHOW_COURSE'
export const LOADING_SHOW_COURSE = 'LOADING_SHOW_COURSE'
export const END_LOADING_SHOW_COURSE = 'END_LOADING_SHOW_COURSE'
export const GET_RECOMMENDED_COURSES = 'GET_RECOMMENDED_COURSES'
export const ERR_GET_RECOMMENDED_COURSES = 'ERR_GET_RECOMMENDED_COURSES'

export const ENROLLED_COURSES = 'ENROLLED_COURSES'

export const ENROLLING_COURSE = 'ENROLLING_COURSE'
export const ERROR_ENROLLING_COURSE = 'ERROR_ENROLLING_COURSE'
export const COURSE_IS_ENROLLED = 'COURSE_IS_ENROLLED'

export const PLAY_COURSE = 'PLAY_COURSE'
export const ERR_PLAY_COURSE = 'ERR_PLAY_COURSE'
export const SAVE_PLAYING_MODULES = 'SAVE_PLAYING_MODULES'
export const PLAY_MODULES = 'PLAY_MODULES'
export const EMPTY_PLAY_MODULES = 'EMPTY_PLAY_MODULES'
export const NULL_ERR_PLAY_COURSE = 'NULL_ERR_PLAY_COURSE'
export const DISPLAY_QUESTIONS = 'DISPLAY_QUESTIONS'
export const HIDE_DISPLAY_QUESTIONS = 'HIDE_DISPLAY_QUESTIONS'
export const ERR_COURSE_IS_ENROLLED = 'ERR_COURSE_IS_ENROLLED'
export const CHECK_COURSE_PROGRESS = 'CHECK_COURSE_PROGRESS'
export const ACCOUNT_TYPE = 'ACCOUNT_TYPE'
export const TOGGLE_LOGIN_FORM = 'TOGGLE_LOGIN_FORM'
export const NULL_AUTH_ERRORS = 'NULL_AUTH_ERRORS'
export const NULL_ERR_FETCH_COURSES = 'NULL_ERR_FETCH_COURSES'
    /**
     * main Category
     */
export const MAIN_CATEGORIES = 'MAIN_CATEGORIES'
export const SUB_CATEGORIES = 'SUB_CATEGORIES'
export const ERR_SUB_CATEGORIES = 'ERR_SUB_CATEGORIES'
export const ERR_MAIN_CATEGORIES = 'ERR_MAIN_CATEGORIES'
export const NULL_ERR_MAIN_CATEGORIES = 'NULL_ERR_MAIN_CATEGORIES'
export const LOAD_SUB = 'LOAD_SUB'

/***
 * review
 */
export const START_COURSE_REVIEW = 'START_COURSE_REVIEW'
export const START_SHOW_COURSE_REVIEW = 'START_SHOW_COURSE_REVIEW'
export const SHOW_COURSE_REVIEW = 'SHOW_COURSE_REVIEW'
export const END_SHOW_COURSE_REVIEW = 'END_SHOW_COURSE_REVIEW'
export const END_COURSE_REVIEW = 'END_COURSE_REVIEW'
export const START_DELETE_REVIEW = 'START_DELETE_REVIEW'
export const END_DELETE_REVIEW = 'END_DELETE_REVIEW'

/**
 * Module Question
 */
export const SHOW_RESULT = 'SHOW_RESULT'
export const RESULT = 'RESULT'
export const HIDE_RESULT = 'HIDE_RESULT'
export const ERR_RESULT = 'ERR_RESULT'
export const CHECK_IF_USER_TOOK_COURSE = 'CHECK_IF_USER_TOOK_COURSE'

/**
 * Course Progress
 */
export const GET_USER_COURSE_PROGRESS = 'GET_USER_COURSE_PROGRESS'
export const ERROR_IN_COURSE_PROGRESS = 'ERROR_IN_COURSE_PROGRESS'
export const GETTING_PROGRESS_STATUS = 'GETTING_PROGRESS_STATUS'
export const STOPPED_PROGRESS_STATUS = 'STOPPED_PROGRESS_STATUS'

/**
 * Utility loader
 */
export const WORKING = 'WORKING'
export const STOPPED_WORKING = 'STOPPED_WORKING'
export const APP_IS_BUSY = 'APP_IS_BUSY'
export const APP_IS_NOT_BUSY = 'APP_IS_NOT_BUSY'

/**
 * comments
 */

export const POST_COMMENT = 'POST_COMMENT'
export const POSTING_COMMENT_ERROR = 'POSTING_COMMENT_ERROR'
export const COMMENT_POSTED = 'COMMENT_POSTED'

export const UPDATE_COMMENT = 'UPDATE_COMMENT'
export const UPDATING_COMMENT = 'UPDATING_COMMENT'
export const COMMENT_UPDATED = 'COMMENT_UPDATED'

export const DELETE_COMMENT = 'DELETE_COMMENT'
export const DELETING_COMMENT_ERROR = 'DELETING_COMMENT_ERROR'
export const COMMENT_DELETED = 'COMMENT_DELETED'

export const GET_COMMENT = 'GET_COMMENT'
export const GET_COMMENT_ERROR = 'GET_COMMENT_ERROR'
export const COMMENT = 'COMMENT'
export const IS_REPLY = 'IS_REPLY'

/**
 * Course Search/ Filter
 */

export const SEARCH_RESULT = 'SEARCH_RESULT'
export const START_SEARCH = 'START_SEARCH'
export const SEARCH_RESULT_ERROR = 'SEARCH_RESULT_ERROR'

/**
 * Volunteer 
 */
export const SENDING_VOLUNTEER_FORM = 'SENDING_VOLUNTEER_FORM'
export const VOLUNTEER_FORM_ERROR = 'VOLUNTEER_FORM_ERROR'
export const VOLUNTEER_FORM_SUCCESS = 'VOLUNTEER_FORM_SUCCESS'

/**
 * Coachee 
 */

export const SENDING_COACHEE_FORM = 'SENDING_COACHEE_FORM'
export const COACHEE_FORM_ERROR = 'COACHEE_FORM_ERROR'
export const COACHEE_FORM_SUCCESS = 'COACHEE_FORM_SUCCESS'
export const MENTEE = 'MENTEE'

/**
 * Notification
 */
export const GET_NOTIFICATION = 'GET_NOTIFICATION'
export const NOTIFICATION = 'NOTIFICATION'
export const ERR_GETTING_NOTIFICATION = 'ERR_GETTING_NOTIFICATION'

/**
 * Cart
 */
export const ADD_TO_CART = 'ADD_TO_CART'
export const ADDED_TO_CART = 'ADDED_TO_CART'
export const ERROR_ADDING_TO_CART = 'ERROR_ADDING_TO_CART'
    //get
export const GET_CART_ITEMS = 'GET_CART_ITEMS'
export const CART_ITEMS = 'CART_ITEMS'
export const ERROR_GETTING_CART = 'ERROR_GETTING_CART'

/**
 * BLOG
 */

export const GET_BLOG_POSTS = 'GET_BLOG_POSTS'
export const BLOG_POSTS = 'BLOG_POSTS'
export const ERR_GETTING_BLOG_POST = 'ERR_GETTING_BLOG_POST'
export const ERR_GETTING_BLOG_POSTS = 'ERR_GETTING_BLOG_POSTS'
export const GET_BLOG_POST = 'GET_BLOG_POST'
export const BLOG_POST = 'BLOG_POST'

export const GET_BLOG_CATEGORIES = 'GET_BLOG_CATEGORIES'
export const BLOG_CATEGORIES = 'BLOG_CATEGORIES'
export const ERR_GETTING_BLOG_CATEGORIES = 'ERR_GETTING_BLOG_CATEGORIES'

/**
 * Testimonial
 */

export const GET_TESTIMONIALS = 'GET_TESTIMONIALS'
export const TESTIMONIALS = 'TESTIMONIALS'
export const TESTIMONIALS_ERRORS = 'TESTIMONIALS_ERRORS'